//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResumeProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLReviews
    {
        public int ReviewsID { get; set; }
        public string ReviewsNameSurname { get; set; }
        public string ReviewsJob { get; set; }
        public string ReviewsMessage { get; set; }
        public string ReviewsImage { get; set; }
    }
}
